name: Build and Release

env:
  VERSION: "v0.3.1"

on:
  push:
    branches:
      - master
#    tags:
#      - 'v*' # Triggers on any tag starting with 'v'

jobs:
  build:
    strategy:
      fail-fast: false
      # Creates two distinct parallel jobs: one for AMD64, one for ARM64
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    name: Build for ${{ matrix.arch }}

    outputs:
      arch: ${{ matrix.arch }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o cgroup_exporter

    - name: Rename
      run: mv cgroup_exporter cgroup_exporter-${{ matrix.arch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: cgroup_exporter-${{ env.VERSION }}-${{ matrix.arch }}
        path: cgroup_exporter-${{ matrix.arch }}
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
        contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        pattern: cgroup_exporter-*
        merge-multiple: true

    - name: Make artifact executable
      run: chmod +x cgroup_exporter-*

    - name: Create tar archive
      run: tar -czvf cgroup_exporter-${{ env.VERSION }}-binaries.tar.gz cgroup_exporter-*
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: cgroup_exporter-${{ env.VERSION }}-binaries.tar.gz
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        prerelease: false
