name: Build and Release

env:
  VERSION: "v0.3.1"

on:
  push:
    branches:
      - master
#    tags:
#      - 'v*' # Triggers on any tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      arch: ${{ runner.arch }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o cgroup_exporter

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: cgroup_exporter-${{ env.VERSION }}-${{ runner.arch }}
        path: cgroup_exporter

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
        contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: cgroup_exporter-${{ env.VERSION }}-${{ needs.build.outputs.arch }}

    - name: Make artifact executable
      run: chmod +x cgroup_exporter

    - name: Rename executable
      run: mv cgroup_exporter cgroup_exporter-${{ env.VERSION }}-${{ needs.build.outputs.arch }}

    - name: Create tar archive
      run: tar -czvf cgroup_exporter-${{ env.VERSION }}-${{ needs.build.outputs.arch }}.tar.gz cgroup_exporter-${{ env.VERSION }}-${{ needs.build.outputs.arch }}
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: cgroup_exporter-${{ env.VERSION }}-${{ needs.build.outputs.arch }}.tar.gz
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        prerelease: false
